library/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')),
]

library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app'

urlpatterns = [
  path('index/', views.index, name='index'),
  path('', views.register, name='register'),
  path('login/', views.log, name='login'),
  path('create/', views.create_book, name='create_book'),
  path('delete/<int:id>', views.delete, name='delete'),
]

library_app/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
  Book_Name = models.CharField(max_length=50)
  Author = models.CharField(max_length=50)
  Price = models.IntegerField()
  Description = models.CharField(max_length=200)

  def __str__(self):
    return self.Book_Name
  

class registration_table(models.Model):
  username = models.CharField(max_length=50)
  password = models.CharField(max_length=50)
  email = models.EmailField()

  def __str__(self):
    return self.username

library_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import registration_table, Book
# for islowercase.. removing case sensivity
from django.db.models import Q

# Create your views here.
def index(request):
    if request.method == 'POST':
        # input value
        author = request.POST.get('author_name')
        if author:
            obj = Book.objects.filter(Q(Author__iexact=author))
            return render(request, 'index.html', {"objects":obj})
        else:
            obj = Book.objects.all()
            return render(request, 'index.html', {"objects":obj})
    obj = Book.objects.all()
    return render(request, 'index.html', {"objects":obj})

# registration
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        if not username:
            messages.error(request, 'Username is required.')
            return redirect('library_app:register')
        if registration_table.objects.filter(username=username).exists():
            messages.error(request, 'Username Already Exists..')
            return redirect('library_app:register')
        elif registration_table.objects.filter(email=email).exists():
            messages.error(request, 'Email Already Exists..')
            return redirect('library_app:register')
        else:
            obj = registration_table.objects.create(username=username, email=email, password=password)
            obj.save()
            if obj:
                return redirect('library_app:login')
            else:
                messages.error(request, 'Authentication failed.')
                return redirect('library_app:register')
    return render(request, 'register.html')

# login
def log(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = registration_table.objects.filter(email=email, password=password)
        if user:
            return redirect('library_app:index')
        else:
            messages.error(request, 'Email or Password is invalid.')
    return render(request, 'login.html')

# create user
def create_book(request):

    if request.method == 'POST':
        book_name = request.POST.get('book')
        author = request.POST.get('author')
        price = request.POST.get('price')
        description = request.POST.get('description')

        if book_name and author and price:
            obj = Book.objects.create(Book_Name = book_name, Author = author, Price = price, Description= description)
            obj.save()
        else:
            return render(request, 'create_book.html')

    
    return render(request, 'create_book.html')

def delete(request, id):
    delete_item = Book.objects.filter(id = id)
    delete_item.delete()
    return redirect('library_app:index')

templates/create_book.html
{% include 'head.html' %}

<div class="create-book-container">
  <div class="create-book">
    <h2>Create a New Book</h2>
    <form action="" method="post">
      {% csrf_token %}
      <input type="text" name="book" placeholder="Book Name" />
      <input type="text" name="author" placeholder="Author Name" />
      <input type="number" name="price" placeholder="Price" />
      <input type="text" name="description" placeholder="Description" />
      <button type="submit">Create</button>
    </form>
    <h3><a href="{% url 'library_app:index' %}">Back 🏠</a></h3>
  </div>
</div>

{% include 'footer.html'%}

templates/footer.html
<footer>
  <div class="container">
    <div class="text">© 2023 Festus Sabu. All rights reserved.</div>
  </div>
</footer>

templates/head.html
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Book Site</title>
<script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>

<style>
  /* footer */
  body {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  footer .container {
    background-color: #000000;
    position: fixed;
    z-index: 10;
    bottom: 0;
    width: 100%;
    height: 100px;
    display: flex;
    align-items: end;
    justify-content: center;
  }
  footer .container .text {
    font-weight: bold;
    font-size: 18px;
    color: #ffffff;
    padding: 5px;
    font-family: monospace;
  }

  /* header */
  header .container {
    background-color: #dfdfdf;
    height: 85px;
    width: 100%;
    align-items: center;
    justify-content: space-between;
    display: flex;
  }
  header .container .header-img img {
    height: 4.5rem;
    width: 4.5rem;
    object-fit: cover;
    border-radius: 50%;
    margin-left: 1rem;
  }
  header .search-container {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 5px;
  }
  header .search-container .input-field {
    min-width: 20rem;
    font-size: 18px;
    padding: 12px;
    outline: none;
  }
  header .search-container .search-button {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 10px 15px;
    cursor: pointer;
  }
  header .container .links ul li {
    list-style: none;
  }
  header .container .links ul li a {
    padding: 6px;
    text-decoration: none;
    font-size: 16px;
    font-family: monospace;
    color: black;
    border-right: 1px solid;
  }
  header .container .links ul li a:last-child {
    margin-right: 10px;
    border-right: none;
  }
  /* sign up page */
  main {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
    font-family: monospace;
    width: 100%;
    background-image: linear-gradient(to right, rgb(216, 149, 149), yellow);
  }
  main .container {
    box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.3);
  }
  main .container form {
    width: 30rem;
    height: 60%;
    padding: 10px;
  }
  main .container form .form-container {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  main .container form h1 {
    font-size: 3rem;
    text-align: center;
    margin-bottom: 2rem;
  }
  main .container form .form-container label {
    font-size: 20px;
  }
  main .container form .form-container input {
    padding: 12px 20px;
    outline: none;
    font-size: 18px;
  }
  main .container form button {
    padding: 12px 20px;
    margin-top: 2rem;
    cursor: pointer;
    width: 100%;
    background-color: rgb(4, 132, 4);
    border: none;
    border-radius: 5px;
    font-size: 20px;
    font-weight: bold;
    color: white;
  }
  /* login page */
  .login-page {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
    font-family: monospace;
    width: 100%;
    background-image: linear-gradient(to right, rgb(216, 149, 149), yellow);
  }
  .login-page .login-container {
    box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.3);
    width: 30rem;
    height: 42%;
    padding: 10px;
  }
  .login-page .login-container h1 {
    font-size: 3rem;
    text-align: center;
    margin-bottom: 2rem;
  }
  .login-page .login-container form .login {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .login-page .login-container form .login label {
    font-size: 20px;
  }
  .login-page .login-container form .login input {
    padding: 12px 20px;
    outline: none;
    font-size: 18px;
  }
  .login-page .login-container form button {
    padding: 12px 20px;
    margin-top: 2rem;
    cursor: pointer;
    width: 100%;
    background-color: rgb(4, 132, 4);
    border: none;
    border-radius: 5px;
    font-size: 20px;
    font-weight: bold;
    color: white;
  }

  section .card-container {
    padding: 20px;
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-gap: 0.7rem;
    grid-row-gap: 1rem;
    font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
      Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
      sans-serif;
    margin-bottom: 7rem;
  }
  section .card-container .card {
    border: 1px solid #000;
    padding: 10px;
  }
  section .card-container .card button {
    padding: 5px;
  }
  section .card-container .card button a {
    text-decoration: none;
  }
  section .card-container .card p {
    font-size: 1.25rem;
    font-weight: bold;
  }
  section .card-container .card p:last-child {
    font-weight: normal;
  }
  section .card-container .card h1 {
    font-size: 2rem;
  }
  section .card-container .card .author {
    padding: 5px 2px;
    color: #fff;
  }
  section .card-container .card .author span {
    background-color: green;
    padding: 5px 10px;
  }
  section .card-container .card .cash {
    padding: 5px 2px;
    color: #fff;
  }
  section .card-container .card .cash span {
    background-color: red;
    padding: 5px 10px;
  }

  .create-book-container {
    display: flex;
    height: 100vh;
    width: 100%;
    align-items: center;
    justify-content: center;
    font-family: monospace;
    background-image: linear-gradient(
      to right,
      rgb(124, 217, 134),
      rgb(43, 86, 137)
    );
  }
  .create-book-container .create-book {
    display: flex;
    flex-direction: column;
    box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.3);
    padding: 20px;
    height: auto;
    text-align: center;
    width: 20%;
  }
  .create-book-container .create-book h2 {
    font-size: 1.5rem;
  }
  .create-book-container .create-book h3 {
    cursor: pointer;
    font-size: 20px;
  }

  .create-book-container .create-book h3 a {
    text-decoration: none;
    color: black;
  }
  .create-book-container .create-book form {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .create-book-container .create-book form input {
    padding: 12px 30px;
    font-size: 20px;
    outline: none;
  }
  .create-book-container .create-book form input::placeholder {
    color: black;
  }
  .create-book-container .create-book form button {
    padding: 12px 30px;
    font-size: 20px;
    margin-top: 1rem;
    cursor: pointer;
  }
</style>

templates/header.html
{% load static %}
<header>
  <div class="container">
    <div class="header-img">
      <img src="{% static 'header_img.jpg' %}" alt="Header img" />
   </div>

    <form action="" method="post">
      {% csrf_token %}
      <div class="search-container">
        <input type="text" class="input-field" placeholder="Search For Author" name="author_name"></input>
        <button class="search-button" type="submit"><box-icon name='search'></box-icon></button>
      </div>
    </form>

    <div class="links">
      <ul>
        <li>
          <a href="{% url 'library_app:create_book' %}">Create Book</a>
          <a href="{% url 'library_app:register' %}">Sign Out</a>
        </li>
      </ul>
    </div>
  </div>
</header>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- head -->
    {% include 'head.html' %}
  </head>
  <body>
    <!-- header -->
    {% include 'header.html' %}
    <!-- block content -->
    {% block content %}
    <!-- contents -->
    {% include 'main.html' %}
    <!-- end block -->
    {% endblock content %}
    <!-- footer -->
    {%include 'footer.html' %}
  </body>
</html>

templates/login.html
<!-- head -->
{% include "head.html" %}

<div class="login-page">
  <div class="login-container">
    <h1>Log In</h1>
    <form action="" method="post">
      {% csrf_token %}
      <div class="login">
        <label>Email</label>
        <input type="email" placeholder="Email" name="email" />
        <label>Password</label>
        <input type="password" placeholder="Password" name="password" />
      </div>
      <button type="submit">LOG IN</button>
      <h3>
        <a href="{% url 'library_app:register' %}">Sign Up</a>
      </h3>
    </form>
    {% for message in messages %}
    <h2 style="color: red; text-align: center">{{message}}</h2>
    {% endfor %}
  </div>
</div>
<!-- footer -->
{% include "footer.html" %}

templates/main.html
<!-- start -->
{% block content %}
<!-- contents -->

<section>
  <div class="card-container">
    {% for i in objects %}
    <div class="card">
      <h1>Name: {{i.Book_Name}}</h1>
      <p class="author"><span>Author: {{i.Author}}</span></p>
      <p class="cash"><span>Price: {{i.Price}}</span></p>
      <p>{{ i.Description }}</p>
      <button>
        <a href="{% url 'library_app:delete' i.id %}"
          ><box-icon name="trash"></box-icon
        ></a>
      </button>
    </div>
    {% endfor %}
  </div>
</section>

<!-- end -->
{% endblock content %}

templates/register.html
<!-- head -->
{% include "head.html" %}

<main>
  <div class="container">
    <form action="" method="post">
      {% csrf_token %}
      <h1>LET'S GO...</h1>
      <div class="form-container">
        <label>Full Name</label>
        <input type="text" placeholder="Full Name" name="username" />
        <label>Email</label>
        <input type="email" placeholder="Email" name="email" />
        <label>Phone Number</label>
        <input type="number" placeholder="number" />
        <label>Password</label>
        <input type="password" placeholder="Password" name="password" />
      </div>
      <button type="submit">SUBMIT</button>
      <h3>
        <a href="{% url 'library_app:login' %}">Log In</a>
      </h3>
    </form>
    {% for message in messages %}
    <h1 style="color: red; text-align: center">{{message}}</h1>
    {% endfor %}
  </div>
</main>

<!-- footer -->
{% include "footer.html" %}

templates/signUp.html
<!-- head -->
{% include "head.html" %}

<main>
  <div class="container">
    <form action="" method="post">
      {% csrf_token %}
      <h1>Sign Up</h1>
      <div class="form-container">
        <label>Full Name</label>
        <input type="text" placeholder="Full Name" />
        <label>Email</label>
        <input type="email" placeholder="Email" />
        <label>Phone Number</label>
        <input type="number" placeholder="number" />
        <label>Password</label>
        <input type="password" placeholder="Password" />
      </div>
      <button type="submit">SUBMIT</button>
    </form>
  </div>
</main>

<!-- footer -->
{% include "footer.html" %}